/**
 * Error codes for API responses
 */
export const ErrorCodes = {
  // Authentication & Authorization
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_FIELD: "MISSING_FIELD",

  // Resource Errors
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  FUND_APPLICATION_NOT_FOUND: "FUND_APPLICATION_NOT_FOUND",
  CASH_BILL_NOT_FOUND: "CASH_BILL_NOT_FOUND",

  // Conflict Errors
  CONFLICT_ERROR: "CONFLICT_ERROR",
  NIM_ALREADY_EXISTS: "NIM_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // Business Logic
  BUSINESS_LOGIC_ERROR: "BUSINESS_LOGIC_ERROR",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  PAYMENT_ALREADY_SUBMITTED: "PAYMENT_ALREADY_SUBMITTED",
  ALREADY_REVIEWED: "ALREADY_REVIEWED",

  // File Upload
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",

  // Database
  DATABASE_ERROR: "DATABASE_ERROR",
  CONNECTION_ERROR: "CONNECTION_ERROR",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
